import './globals.css'
import { Geist, Geist_Mono } from 'next/font/google'
import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server'
import { Navbar } from './components/General/Navbar'
import { AuthProvider } from './components/General/AuthProvider'
import { PageTransition } from './components/General/PageTransition'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'BlogCraft',
  description: 'Generated by create next app',
}
type User = {
  given_name?: string;
  picture?: string;
} | null;


export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const { getUser } = getKindeServerSession()
  const rawUser = await getUser();
  const user: User = rawUser
  ? {
      given_name: rawUser.given_name as string | undefined,
      picture: rawUser.picture as string | undefined,
    }
  : null;


  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <body className="bg-background text-foreground min-h-screen relative overflow-x-hidden">

        <div className="absolute inset-0 -z-10">
          <div className="absolute top-0 right-0 h-[800px] w-[800px] -translate-x-[40%] translate-y-[10%] rounded-full bg-[rgba(173,109,244,0.4)] opacity-40 blur-[140px]" />
          <div className="absolute bottom-0 left-0 h-[600px] w-[600px] translate-x-[-30%] translate-y-[20%] rounded-full bg-[rgba(109,244,173,0.3)] opacity-30 blur-[120px]" />
        </div>

        <AuthProvider>
          <div className="max-w-7xl mx-auto p-4 sm:pt-6 lg:px-8">
            <Navbar user={user} />
            <PageTransition>
              {children}
            </PageTransition>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
